routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::get('/', 'ProductsController@index');
 
Route::get('cart', 'ProductsController@cart');
 
Route::get('add-to-cart/{id}', 'ProductsController@addToCart');

Route::patch('update-cart', 'ProductsController@update');
 
Route::delete('remove-from-cart', 'ProductsController@remove');

Route::get('/cart/redirection', 'ProductsController@redirectionCheckout');

Route::get('/response', 'ProductsController@statusCheckout');

Route::get('/pendientes', 'ProductsController@statusSonda');

Route::resource('productos', 'ProductoController');

Route::resource('pedidos', 'PedidoController');

app/Http/Controllers/PedidoController.php
<?php

namespace App\Http\Controllers;
use App\Product;
use App\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PedidoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pedidos = Transaction::join('products', 'products.sku', 'transactions.product_sku')
        ->select('transactions.*', 'products.sku', 'products.name', 'products.price')
        ->get();

        return view('pedidos.index', compact('pedidos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pedidos/index.blade.php
@extends('layouts.app', ['activePage' => 'pedidos-list', 'titlePage' => __('Gestionar pedidos')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('pedidos') }}</h4>
                <p class="card-category"> {{ __('Gestionar pedidos') }}</p>
              </div>
              <div class="card-body">
                @if (session()->get('success'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session()->get('success') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right">
                    
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table" id="tabla_pedido">
                    <thead class=" text-primary">
                      <th>
                          {{ __('Producto') }}
                      </th>
                      <th>
                          {{ __('Nombre del cliente') }}
                      </th>
                      <th>
                          {{ __('Método de pago') }}
                      </th>
                      <th>
                          {{ __('Estado') }}
                      </th>
                      <th>
                          {{ __('Valor') }}
                      </th>
                      <th>
                        {{ __('Fecha de creación') }}
                      </th>
                      <th class="text-right">
                        {{ __('Acciones') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($pedidos as $pedido)
                        <tr>
                          <td>
                            {{ $pedido->name }}
                          </td>
                          <td>
                            {{ $pedido->customer_name }}
                          </td>
                          <td>
                            {{ $pedido->payment_method }}
                          </td>
                          <td>
                            @if($pedido->status == 'APPROVED')
                            <div class="status green">
                            Aprobada
                            </div>
                            @endif
                            @if($pedido->status == 'PENDING')
                            <div class="status orange">
                            Pendiente
                            </div>
                            @endif
                            @if($pedido->status == 'REJECTED')
                            <div class="status red">
                            Rechazada
                            </div>
                            @endif
                          </td>
                          <td>
                            {{ $pedido->total }}
                          </td>
                          <td>
                            {{ $pedido->created_at }}
                          </td>
                          <td class="td-actions text-right">
                              <form action="{{ route('pedidos.destroy', $pedido->id)}}" style="display: inline-block;" method="post">
                              @csrf
                              @method('delete')
                          
                              <!-- <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('pedidos.edit', $pedido) }}" data-original-title="" title="">
                                <i class="material-icons">edit</i>
                                <div class="ripple-container"></div>
                              </a> -->
                              <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Estas seguro que deseas eliminar el pedido?") }}') ? this.parentElement.submit() : ''">
                                  <i class="material-icons">close</i>
                                  <div class="ripple-container"></div>
                              </button>
                             </form>
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              




            </div>
        </div>
      </div>
    </div>
  </div>
@endsection